import { WorldGraph, WorldNode, WorldEdge, WorldSpec } from '@/types/world';
import { SeedRandom } from './SeedRandom';

export class WorldGraphGenerator {
  public static generate(_spec: WorldSpec, _rng: SeedRandom): WorldGraph {
    // 1. Establish Primary World Nodes
    const nodes: WorldNode[] = [
      // Settlements
      {
        id: 'node_crownport',
        name: 'Crownport',
        type: 'city',
        biome: 'city',
        x: 180,
        y: 110,
        regionId: 'region_crownport',
        importance: 5,
        description: 'The bustling metropolis and seat of the Tideguard Admiralty.',
      },
      {
        id: 'node_oakhaven',
        name: 'Oakhaven',
        type: 'village',
        biome: 'forest',
        x: 80,
        y: 125,
        regionId: 'region_oakhaven',
        importance: 4,
        description: 'A cozy forest village built around an ancient giant oak.',
      },
      {
        id: 'node_tidebreak',
        name: 'Tidebreak',
        type: 'village',
        biome: 'beach',
        x: 70,
        y: 200,
        regionId: 'region_tidebreak',
        importance: 4,
        description: 'A rugged fishing community built on wave-battered stilt piers.',
      },
      {
        id: 'node_cragwatch',
        name: 'Cragwatch',
        type: 'town',
        biome: 'mountain',
        x: 205,
        y: 50,
        regionId: 'region_cragwatch',
        importance: 4,
        description: 'A high alpine mining stronghold perched on slate cliffs.',
      },

      // Dungeons & Shrines
      {
        id: 'node_sunken_crypt',
        name: 'Sunken Crypt of the Tide King',
        type: 'dungeon',
        biome: 'ocean',
        x: 215,
        y: 195,
        regionId: 'region_azure_coast',
        importance: 4,
        description: 'Drowned catacombs half-submerged in the tidal waters of Azure Coast.',
      },
      {
        id: 'node_echoing_chasm',
        name: 'Echoing Chasm',
        type: 'dungeon',
        biome: 'mountain',
        x: 245,
        y: 40,
        regionId: 'region_cragwatch',
        importance: 3,
        description: 'A labyrinth of crystal caverns and abandoned silver mine shafts.',
      },
      {
        id: 'node_elderwood_shrine',
        name: 'Elderwood Shrine',
        type: 'shrine',
        biome: 'deepwood',
        x: 50,
        y: 40,
        regionId: 'region_deepwood',
        importance: 3,
        description: 'An ancient stone temple wrapped in primeval roots and glowing moss.',
      },

      // Landmarks & Crossroad Junctions
      {
        id: 'node_crossroads_weald',
        name: "Old King's Crossroads",
        type: 'crossroad',
        biome: 'grassland',
        x: 130,
        y: 120,
        regionId: 'region_oakhaven',
        importance: 3,
        description: 'The ancient stone signpost where roads from Crownport, Oakhaven, and the Coast converge.',
      },
      {
        id: 'node_crossroads_mountain',
        name: "Dragon's Spine Junction",
        type: 'crossroad',
        biome: 'mountain_pass',
        x: 175,
        y: 75,
        regionId: 'region_cragwatch',
        importance: 3,
        description: 'The windy high pass dividing the lush lowlands from the frozen peaks.',
      },
      {
        id: 'node_smugglers_cove',
        name: "Smuggler's Cove",
        type: 'landmark',
        biome: 'coastal_rock',
        x: 135,
        y: 195,
        regionId: 'region_azure_coast',
        importance: 2,
        description: 'A secluded sea cavern concealed behind natural stone sea arches.',
      },
      {
        id: 'node_overlook_vista',
        name: 'Mistfall Scenic Overlook',
        type: 'landmark',
        biome: 'mountain',
        x: 235,
        y: 65,
        regionId: 'region_cragwatch',
        importance: 2,
        description: 'A precipitous cliff ledge with a breathtaking panorama of the continent.',
      },
      {
        id: 'node_weald_fairy_glade',
        name: 'The Moonlit Glade',
        type: 'poi',
        biome: 'deepwood',
        x: 85,
        y: 45,
        regionId: 'region_deepwood',
        importance: 2,
        description: 'A mystical fairy ring where rare bioluminescent flora thrives.',
      },
      {
        id: 'node_abandoned_cottage',
        name: 'Abandoned Woodcutter Lodge',
        type: 'poi',
        biome: 'forest',
        x: 110,
        y: 85,
        regionId: 'region_oakhaven',
        importance: 2,
        description: 'A decaying timber lodge overgrown with ivy and wild berries.',
      },
      {
        id: 'node_secret_grotto',
        name: 'Hidden Waterfall Grotto',
        type: 'secret',
        biome: 'forest',
        x: 105,
        y: 155,
        regionId: 'region_oakhaven',
        importance: 1,
        description: 'A hidden grotto tucked behind a cascading river curtain.',
      },
      {
        id: 'node_shipwreck_cove',
        name: 'Sorrow Cove Shipwreck',
        type: 'poi',
        biome: 'beach',
        x: 115,
        y: 220,
        regionId: 'region_azure_coast',
        importance: 2,
        description: 'The barnacle-encrusted ribs of the Pale Leviathan frigate on the south beach.',
      },
      {
        id: 'node_island_shrine',
        name: 'Secluded Sandbar Shrine',
        type: 'secret',
        biome: 'beach',
        x: 100,
        y: 215,
        regionId: 'region_tidebreak',
        importance: 1,
        description: 'A forgotten stone altar reachable only at low tide across stepping stones.',
      },
    ];

    // 2. Establish World Edges (Traversable Paths & Routes)
    const edges: WorldEdge[] = [
      // Major Highways
      {
        id: 'edge_crownport_to_crossroads_weald',
        fromNodeId: 'node_crownport',
        toNodeId: 'node_crossroads_weald',
        routeType: 'paved_road',
        name: "Old King's Highway (East)",
      },
      {
        id: 'edge_crossroads_weald_to_oakhaven',
        fromNodeId: 'node_crossroads_weald',
        toNodeId: 'node_oakhaven',
        routeType: 'paved_road',
        name: 'Oakhaven Timber Way',
      },
      {
        id: 'edge_crossroads_weald_to_tidebreak',
        fromNodeId: 'node_crossroads_weald',
        toNodeId: 'node_tidebreak',
        routeType: 'dirt_trail',
        name: 'Tidebreak Salt Trail',
      },
      {
        id: 'edge_crownport_to_crossroads_mountain',
        fromNodeId: 'node_crownport',
        toNodeId: 'node_crossroads_mountain',
        routeType: 'paved_road',
        name: 'Highland Merchant Road',
      },
      {
        id: 'edge_crossroads_mountain_to_cragwatch',
        fromNodeId: 'node_crossroads_mountain',
        toNodeId: 'node_cragwatch',
        routeType: 'mountain_pass',
        name: "Dragon's Spine Pass",
      },
      {
        id: 'edge_crownport_to_azure_coast',
        fromNodeId: 'node_crownport',
        toNodeId: 'node_sunken_crypt',
        routeType: 'coastal_path',
        name: 'Azure Shoreline Promenade',
      },
      {
        id: 'edge_tidebreak_to_shipwreck_cove',
        fromNodeId: 'node_tidebreak',
        toNodeId: 'node_shipwreck_cove',
        routeType: 'coastal_path',
        name: 'Sorrow Cove Shore Path',
      },

      // Regional Connections & Secondary Routes
      {
        id: 'edge_oakhaven_to_deepwood',
        fromNodeId: 'node_oakhaven',
        toNodeId: 'node_weald_fairy_glade',
        routeType: 'dirt_trail',
        name: 'Whispering Glade Trail',
      },
      {
        id: 'edge_deepwood_to_elderwood_shrine',
        fromNodeId: 'node_weald_fairy_glade',
        toNodeId: 'node_elderwood_shrine',
        routeType: 'dirt_trail',
        name: 'Ancient Pilgrim Path',
      },
      {
        id: 'edge_crossroads_weald_to_abandoned_cottage',
        fromNodeId: 'node_crossroads_weald',
        toNodeId: 'node_abandoned_cottage',
        routeType: 'dirt_trail',
        name: 'Woodcutter Trail',
      },
      {
        id: 'edge_cragwatch_to_echoing_chasm',
        fromNodeId: 'node_cragwatch',
        toNodeId: 'node_echoing_chasm',
        routeType: 'mountain_pass',
        name: 'Mine Cart Rail Track',
      },
      {
        id: 'edge_cragwatch_to_overlook_vista',
        fromNodeId: 'node_cragwatch',
        toNodeId: 'node_overlook_vista',
        routeType: 'mountain_pass',
        name: 'High Ridge Footpath',
      },

      // Secrets & Hidden Passages
      {
        id: 'edge_tidebreak_to_smugglers_cove',
        fromNodeId: 'node_tidebreak',
        toNodeId: 'node_smugglers_cove',
        routeType: 'hidden_trail',
        name: 'Low Tide Smuggler Run',
        isSecret: true,
      },
      {
        id: 'edge_oakhaven_to_secret_grotto',
        fromNodeId: 'node_oakhaven',
        toNodeId: 'node_secret_grotto',
        routeType: 'hidden_trail',
        name: 'Overgrown River Path',
        isSecret: true,
      },
      {
        id: 'edge_tidebreak_to_island_shrine',
        fromNodeId: 'node_tidebreak',
        toNodeId: 'node_island_shrine',
        routeType: 'hidden_trail',
        name: 'Stepping Stone Reef',
        isSecret: true,
      },
    ];

    return { nodes, edges };
  }
}
